name: Count lines in all repos

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  count_lines:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Count lines of code
      run: |
        git clone https://github.com/Maximelego/Maximelego.git
        cloc --by-file-by-lang . > lines_of_code.txt
    - name: Update README
      run: |
        echo "Total lines of code: $(cat lines_of_code.txt)" >> README.md