name: Count lines in all repos

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

jobs:
  count_lines:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install cloc
      run: |
        sudo apt-get update
        sudo apt-get install cloc

    - name: Clone repository
      run: |
        git clone https://github.com/Maximelego/Maximelego.git

    - name: Count lines of code
      run: |
        cloc --by-file-by-lang Maximelego > lines_of_code.txt

    - name: Update README
      run: |
        echo "Total lines of code: $(cat lines_of_code.txt)" >> README.md
