name: Update README with recent activity

on:
  schedule:
    # Runs at 12:00 UTC every day
    - cron: "0 12 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: jamesgeorge007/github-activity-readme@v0.1.0
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
